# Generated by Django 5.2.8 on 2025-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_results_date_alter_results_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True),
        ),
    ]
