# Generated by Django 5.2.8 on 2025-11-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_student_date_of_birth_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10),
        ),
    ]
